//add action types
export const ADD_USER = "ADD_USER"
export const UPDATE_LANGUAGELEVELSTATUS = "UPDATE_LANGUAGELEVELSTATUS"
export const FIND_PARTNER = "FIND_PARTNER"
export const INCREMENT_SESSTIONCOUNT = "INCREMENT_SESSTIONCOUNT"